import {rollDice,diceTokens} from '@/lib/roleplay';
import {database} from '@/db/raw';
type Row=Record<string,any>;
const now=()=>new Date().toISOString(),id=()=>crypto.randomUUID();
const fail=(message:string,status=400)=>{throw Object.assign(new Error(message),{status})};
const hex=(a:ArrayBuffer)=>Array.from(new Uint8Array(a),b=>b.toString(16).padStart(2,'0')).join('');
async function digest(s:string){return hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))}
async function hash(s:string,salt=hex(crypto.getRandomValues(new Uint8Array(16)).buffer)){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(s),'PBKDF2',false,['deriveBits']);return salt+':'+hex(await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(salt),iterations:100000,hash:'SHA-256'},k,256))}
async function verify(s:string,h:string){const actual=await hash(s,h.split(':')[0]);let d=actual.length^h.length;for(let i=0;i<h.length;i++)d|=actual.charCodeAt(i)^h.charCodeAt(i);return d===0}
function str(v:unknown,min:number,max:number,label:string){if(typeof v!=='string'||v.trim().length<min||Array.from(v).length>max)fail(`${label}: ${min}~${max}자로 입력해 주세요.`);return (v as string).trim()}
const cookie=(r:Request,k:string)=>r.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith(k+'='))?.slice(k.length+1)||'';
export async function GET(req:Request){return handle(req)}
export async function POST(req:Request){return handle(req)}
export async function PATCH(req:Request){return handle(req)}
export async function DELETE(req:Request){return handle(req)}
async function handle(req:Request){
 const headers=new Headers({'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});
 const ok=(data:unknown)=>new Response(JSON.stringify(data),{headers});
 try{
 const url=new URL(req.url),p=url.pathname.replace(/^\/api\//,'').split('/'),method=req.method;
 if(method!=='GET'){const origin=req.headers.get('origin');if(origin&&origin!==url.origin)fail('허용되지 않은 요청입니다.',403);if(!req.headers.get('content-type')?.includes('application/json'))fail('JSON 요청이 필요합니다.',415)}
 const db=database();const q=(sql:string,...args:any[])=>db.prepare(sql).bind(...args);const one=async(sql:string,...args:any[])=>await q(sql,...args).first<Row>();const all=async(sql:string,...args:any[])=>(await q(sql,...args).all<Row>()).results;
 const token=cookie(req,'rp_session');const user=token?await one('SELECT u.id,u.username,u.role FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires>? AND u.active=1',await digest(token),Date.now()):null;
 const auth=()=>{if(!user)fail('로그인이 필요합니다.',401);return user!};const admin=()=>{auth();if(!['SUPER','SUB'].includes(user!.role))fail('관리자 권한이 필요합니다.',403)};
 const log=async(action:string,target:string)=>q('INSERT INTO audit(id,actor,action,target,created) VALUES(?,?,?,?,?)',id(),user?.id||null,action,target,now()).run();
 let b:Row={};if(method!=='GET'){const raw=await req.text();if(raw.length>150000)fail('입력 내용이 너무 큽니다.',413);try{b=JSON.parse(raw||'{}')}catch{fail('잘못된 요청입니다.')}}
 if(p[0]==='maintenance'&&p[1]==='reset'&&method==='POST'){
 const {env}=await import('cloudflare:workers');const key=(env as unknown as Record<string,string>).RESET_TOKEN;
 if(!key||req.headers.get('authorization')!==`Bearer ${key}`||b.confirm!=='RESET_ALL_RP_LAND')fail('허용되지 않은 요청입니다.',403);
 const marker='reset-2026-09-25-v2';if(await one('SELECT id FROM maintenance WHERE id=?',marker))fail('이미 초기화했습니다.',409);
 const tables=['sessions','grants','editors','names','comments','entries','categories','audit','attempts','users'];
 await db.batch([...tables.map(t=>q(`DELETE FROM ${t} WHERE NOT EXISTS(SELECT 1 FROM maintenance WHERE id=?)`,marker)),q('INSERT OR IGNORE INTO maintenance(id) VALUES(?)',marker)]);
 return ok({success:true,counts:Object.fromEntries(await Promise.all(tables.map(async t=>[t,(await one(`SELECT count(*) n FROM ${t}`))!.n])))})
 }
 const rate=async(key:string)=>{const k=await digest(key);await q('INSERT INTO attempts(key,count,expires) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN expires<? THEN 1 ELSE count+1 END,expires=CASE WHEN expires<? THEN excluded.expires ELSE expires END',k,Date.now()+900000,Date.now(),Date.now()).run();const row=await one('SELECT count FROM attempts WHERE key=?',k);if(row!.count>20)fail('시도 횟수가 많습니다. 15분 후 다시 시도해 주세요.',429)};
 if(p[0]==='me'){if(method==='DELETE'){auth();if(user!.role==='SUPER')fail('총관리자 계정은 탈퇴할 수 없습니다.');if(!await verify(String(b.password||''),(await one('SELECT password FROM users WHERE id=?',user!.id))!.password))fail('비밀번호가 일치하지 않습니다.',401);await db.batch([q('UPDATE users SET active=0,password=?,username=? WHERE id=?','',`deleted-${user!.id}`,user!.id),q('DELETE FROM sessions WHERE user_id=?',user!.id),q('DELETE FROM names WHERE user_id=?',user!.id)]);await log('withdraw',user!.id);return ok({success:true})}return ok({user,names:user?await all('SELECT name FROM names WHERE user_id=?',user.id):[],setup:!(await one("SELECT id FROM users WHERE role='SUPER' LIMIT 1"))})}
 if(p[0]==='register'&&method==='POST'){const username=str(b.username,3,30,'아이디');if(!/^[a-zA-Z0-9가-힣_-]+$/.test(username))fail('아이디에는 문자, 숫자, 밑줄, 하이픈만 사용할 수 있습니다.');const password=str(b.password,8,128,'비밀번호');await rate('register:'+username);const uid=id();const hp=await hash(password);try{await q('INSERT INTO users(id,username,password,role,created) VALUES(?,?,?,?,?)',uid,username,hp,'USER',now()).run()}catch{fail('이미 사용 중인 아이디입니다.',409)}return ok({success:true})}
 if(p[0]==='login'&&method==='POST'){const username=str(b.username,1,30,'아이디');await rate('login:'+username);const u=await one('SELECT * FROM users WHERE username=? AND active=1',username);if(!u||!await verify(String(b.password||''),u.password))fail('아이디 또는 비밀번호가 일치하지 않습니다.',401);const t=id()+id();await q('INSERT INTO sessions(token,user_id,expires) VALUES(?,?,?)',await digest(t),u!.id,Date.now()+7*86400000).run();headers.append('Set-Cookie',`rp_session=${t}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=604800`);return ok({success:true})}
 if(p[0]==='logout'&&method==='POST'){if(token)await q('DELETE FROM sessions WHERE token=?',await digest(token)).run();headers.append('Set-Cookie','rp_session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0');return ok({success:true})}
 if(p[0]==='setup'&&method==='POST'){auth();const {env}=await import('cloudflare:workers');const setupToken=(env as unknown as Record<string,string>).ADMIN_SETUP_TOKEN;if(!setupToken||!await digest(String(b.token||'')).then(x=>digest(setupToken).then(y=>x===y)))fail('운영자 설정 키를 확인해 주세요.',403);const r=await q("UPDATE users SET role='SUPER' WHERE id=? AND NOT EXISTS(SELECT 1 FROM users WHERE role='SUPER')",user!.id).run();if(!r.meta.changes)fail('이미 총관리자가 지정되었습니다.',409);await log('setup',user!.id);return ok({success:true})}
 if(p[0]==='users'){if(method==='GET')return ok(await all("SELECT id,CASE WHEN active=1 THEN username ELSE '탈퇴 사용자' END username,role,active FROM users ORDER BY created"));if(p[1]){auth();if(user!.role!=='SUPER')fail('총관리자만 변경할 수 있습니다.',403);if(p[1]===user!.id)fail('자기 계정의 권한은 변경할 수 없습니다.');if(method==='PATCH'){if(!['USER','SUB'].includes(b.role))fail('잘못된 역할입니다.');await q("UPDATE users SET role=? WHERE id=? AND role!='SUPER' AND active=1",b.role,p[1]).run();await log('role:'+b.role,p[1]);return ok({success:true})}if(method==='DELETE'){await db.batch([q("UPDATE users SET active=0,password='',username=? WHERE id=? AND role!='SUPER'",`deleted-${p[1]}`,p[1]),q('DELETE FROM sessions WHERE user_id=?',p[1]),q('DELETE FROM names WHERE user_id=?',p[1])]);await log('deactivate',p[1]);return ok({success:true})}}}
 if(p[0]==='categories'){if(method==='GET')return ok(await all('SELECT * FROM categories ORDER BY name'));admin();if(method==='POST'){const cid=id();await q('INSERT INTO categories(id,name) VALUES(?,?)',cid,str(b.name,1,20,'카테고리')).run();return ok({id:cid})}if(method==='PATCH'){await q('UPDATE categories SET name=? WHERE id=?',str(b.name,1,20,'카테고리'),p[1]).run();return ok({success:true})}}
 if(p[0]==='audit'){admin();return ok(await all('SELECT * FROM audit ORDER BY created DESC LIMIT 100'))}
 if(p[0]==='entries'){
  const eid=p[1];let entry:Row|null=null;
  if(eid==='practice'){await q("INSERT OR IGNORE INTO entries(id,kind,title,content,categories,created,updated) VALUES('practice','practice','연습장','캐릭터의 목소리와 문장, 주사위를 자유롭게 연습하세요. 내가 쓴 댓글은 언제든 수정할 수 있습니다.','[]',?,?)",now(),now()).run()}
  if(!eid&&method==='GET'){const kind=url.searchParams.get('kind')==='wiki'?'wiki':'thread',search=url.searchParams.get('q')||'',cat=url.searchParams.get('category')||'',page=Math.max(1,Number(url.searchParams.get('page'))||1);const where="e.kind=? AND e.deleted=0 AND (e.title LIKE ? ESCAPE '\\' OR (e.secret IS NULL AND e.content LIKE ? ESCAPE '\\')) AND (?='' OR EXISTS(SELECT 1 FROM json_each(e.categories) WHERE value=?))";const pattern='%'+search.replace(/[\\%_]/g,'\\$&')+'%';const args=[kind,pattern,pattern,cat,cat];const rows=await all(`SELECT e.id,e.title,e.kind,e.categories,e.created,e.updated,e.author_id,CASE WHEN u.active=1 THEN u.username ELSE '탈퇴 사용자' END author,e.secret IS NOT NULL is_secret,(SELECT count(*) FROM comments c WHERE c.entry_id=e.id) comment_count FROM entries e LEFT JOIN users u ON u.id=e.author_id WHERE ${where} ORDER BY e.updated DESC LIMIT 20 OFFSET ?`,...args,(page-1)*20);const count=await one(`SELECT count(*) n FROM entries e WHERE ${where}`,...args);return ok({entries:rows,total:count!.n,page})}
  if(!eid&&method==='POST'){auth();const kind=b.kind==='wiki'?'wiki':'thread',title=str(b.title,1,120,'제목'),content=str(b.content,1,kind==='wiki'?50000:5000,'본문');const cats=Array.isArray(b.categories)?[...new Set(b.categories)]:[];if(cats.length>3)fail('카테고리는 최대 3개입니다.');for(const c of cats)if(!await one('SELECT id FROM categories WHERE id=?',c))fail('잘못된 카테고리입니다.');const secret=kind==='thread'&&b.isSecret?await hash(str(b.secretPw,4,128,'비밀글 비밀번호')):null;const eid=id();await q('INSERT INTO entries(id,kind,title,content,author_id,secret,categories,created,updated) VALUES(?,?,?,?,?,?,?,?,?)',eid,kind,title,content,user!.id,secret,JSON.stringify(cats),now(),now()).run();return ok({id:eid})}
  entry=await one("SELECT e.*,CASE WHEN u.active=1 THEN u.username ELSE '탈퇴 사용자' END author FROM entries e LEFT JOIN users u ON u.id=e.author_id WHERE e.id=? AND e.deleted=0",eid);if(!entry)fail('문서를 찾을 수 없습니다.',404);const e=entry!;
  const isAdmin=!!user&&['SUPER','SUB'].includes(user.role),isOwner=user?.id===e.author_id,canEdit=isAdmin||isOwner||!!(user&&await one('SELECT user_id FROM editors WHERE entry_id=? AND user_id=?',eid,user.id));
  if(p[2]==='unlock'&&method==='POST'){await rate('secret:'+eid);if(!e.secret||!await verify(String(b.password||''),e.secret))fail('비밀번호가 일치하지 않습니다.',401);const t=id()+id();await q('INSERT INTO grants(token,entry_id,expires) VALUES(?,?,?)',await digest(t),eid,Date.now()+3600000).run();headers.append('Set-Cookie',`rp_grant_${eid}=${t}; Path=/api/entries/${eid}; HttpOnly; Secure; SameSite=Lax; Max-Age=3600`);await log('unlock',eid);return ok({success:true})}
  if(e.secret){const t=cookie(req,`rp_grant_${eid}`);if(!t||!await one('SELECT token FROM grants WHERE token=? AND entry_id=? AND expires>?',await digest(t),eid,Date.now()))return new Response(JSON.stringify({error:'비밀 스레드입니다. 비밀번호를 입력해 주세요.',locked:true,title:e.title}),{status:403,headers})}
  if(p[2]==='editors'){auth();if(!isAdmin&&!isOwner)fail('작성자만 편집 권한을 공유할 수 있습니다.',403);if(method==='GET')return ok(await all('SELECT u.id,u.username FROM editors x JOIN users u ON u.id=x.user_id WHERE x.entry_id=?',eid));if(method==='POST'){if(!await one('SELECT id FROM users WHERE id=? AND active=1',b.userId))fail('회원을 찾을 수 없습니다.');await q('INSERT OR IGNORE INTO editors(entry_id,user_id) VALUES(?,?)',eid,b.userId).run();return ok({success:true})}if(method==='DELETE'){await q('DELETE FROM editors WHERE entry_id=? AND user_id=?',eid,b.userId).run();return ok({success:true})}}
  if(p[2]==='comments'){
   if(method==='GET')return ok(await all("SELECT c.id,c.author_id,c.character,CASE WHEN c.hidden=0 AND c.deleted=0 THEN c.content ELSE '' END content,c.hidden,c.deleted,CASE WHEN c.hidden=0 AND c.deleted=0 THEN c.dice ELSE NULL END dice,c.created,c.updated,CASE WHEN u.active=1 THEN u.username ELSE '탈퇴 사용자' END author FROM comments c LEFT JOIN users u ON u.id=c.author_id WHERE c.entry_id=? AND (?!='practice' OR c.deleted=0) ORDER BY c.rowid",eid,eid));
   auth();if(method==='POST'){if(e.kind==='wiki')fail('위키에는 댓글을 작성할 수 없습니다.');const character=str(b.character||user!.username,1,30,'캐릭터명'),content=str(b.content,1,1500,'레스');let dice=null;try{const rolls=rollDice(content);if(rolls.length)dice=JSON.stringify(rolls)}catch(error){fail((error as Error).message)}const cid=id();const r=await q("INSERT INTO comments(id,entry_id,author_id,character,content,dice,created,updated) SELECT ?,?,?,?,?,?,?,? WHERE (SELECT count(*) FROM comments WHERE entry_id=? AND (?!='practice' OR deleted=0))<1500",cid,eid,user!.id,character,content,dice,now(),now(),eid,eid).run();if(!r.meta.changes)fail('댓글 1,500개에 도달했습니다.',409);await db.batch([q('INSERT OR IGNORE INTO names(user_id,name) VALUES(?,?)',user!.id,character),q('UPDATE entries SET updated=? WHERE id=?',now(),eid)]);return ok({id:cid})}
   const comment=await one('SELECT * FROM comments WHERE id=? AND entry_id=?',p[3],eid);if(!comment)fail('댓글을 찾을 수 없습니다.',404);
   if(method==='DELETE'){admin();if(e.kind==='practice'){await q("DELETE FROM comments WHERE entry_id=? AND (id=? OR deleted=1)",eid,p[3]).run();await log('delete-practice-comment',p[3]);return ok({success:true})}await q("UPDATE comments SET deleted=1,content='',dice=NULL,character='',updated=? WHERE id=? AND entry_id=?",now(),p[3],eid).run();await log('delete-comment',p[3]);return ok({success:true})}
   if(comment!.deleted)fail('삭제된 레스입니다.',410);
   if(method==='PATCH'){if(typeof b.hidden==='boolean'){if(!isAdmin&&!isOwner)fail('스레드 작성자 또는 관리자만 가릴 수 있습니다.',403);await q('UPDATE comments SET hidden=? WHERE id=?',b.hidden?1:0,p[3]).run();await log(b.hidden?'hide':'unhide',p[3]);return ok({success:true})}if(e.kind!=='practice'||comment!.author_id!==user!.id)fail('연습장에서 내가 쓴 댓글만 수정할 수 있습니다.',403);if(comment!.dice)fail('주사위 결과는 수정할 수 없습니다.',403);const edited=str(b.content,1,1500,'레스');try{if(diceTokens(edited).length)fail('주사위는 새 레스를 등록할 때만 굴릴 수 있습니다.')}catch(error){fail((error as Error).message)}await q('UPDATE comments SET content=?,updated=? WHERE id=?',edited,now(),p[3]).run();return ok({success:true})}
   fail('지원하지 않는 레스 요청입니다.',405);
  }
  if(p[2])fail('요청을 찾을 수 없습니다.',404);
  if(method==='GET'){const {secret,...safe}=e;return ok({...safe,is_secret:!!secret,canEdit:e.kind!=='practice'&&canEdit,canShare:e.kind!=='practice'&&(isAdmin||isOwner),canHide:isAdmin||isOwner,canDeleteComment:isAdmin,canDelete:e.kind!=='practice'&&isAdmin})}
  if(method==='PATCH'){auth();if(!canEdit||e.kind==='practice')fail('편집 권한이 없습니다.',403);const title=str(b.title,1,120,'제목'),content=str(b.content,1,e.kind==='wiki'?50000:5000,'본문'),cats=Array.isArray(b.categories)?[...new Set(b.categories)]:JSON.parse(e.categories);if(cats.length>3)fail('카테고리는 최대 3개입니다.');for(const c of cats)if(!await one('SELECT id FROM categories WHERE id=?',c))fail('잘못된 카테고리입니다.');await q('UPDATE entries SET title=?,content=?,categories=?,updated=? WHERE id=?',title,content,JSON.stringify(cats),now(),eid).run();return ok({success:true})}
  if(method==='DELETE'){admin();if(e.kind==='practice')fail('연습장은 삭제할 수 없습니다.');await q('UPDATE entries SET deleted=1 WHERE id=?',eid).run();await log('delete-entry',eid);return ok({success:true})}
 }
 fail('요청을 찾을 수 없습니다.',404);
 }catch(error){const e=error as Error&{status?:number};if(!e.status)console.error('RP LAND API',e);return new Response(JSON.stringify({error:e.status?e.message:'일시적으로 처리할 수 없습니다. 잠시 후 다시 시도해 주세요.'}),{status:e.status||503,headers})}
}
