import assert from 'node:assert/strict';
const base=process.env.TEST_BASE_URL;assert.match(base,/^http:\/\/127\.0\.0\.1:/);let checks=0;
function check(value,label){assert.ok(value,label);console.log('PASS '+label);checks++}
function client(){let cookies={};return async(path,method='GET',body)=>{const r=await fetch(base+'/api/'+path,{method,headers:{'Content-Type':'application/json',Connection:'close',Cookie:Object.entries(cookies).map(([k,v])=>`${k}=${v}`).join('; ')},body:body===undefined?undefined:JSON.stringify(body)});for(const c of r.headers.getSetCookie()){const[k,...v]=c.split(';')[0].split('=');cookies[k]=v.join('=')}return {status:r.status,data:await r.json()}}}
const superadmin=client(),sub=client(),author=client(),editor=client(),guest=client();
for(const [call,username] of [[superadmin,'category_super'],[sub,'category_sub'],[author,'category_author'],[editor,'category_editor']]){await call('register','POST',{username,password:'Category-test-Password!'});await call('login','POST',{username,password:'Category-test-Password!'})}
await superadmin('setup','POST',{token:process.env.TEST_SETUP_TOKEN});const sid=(await sub('me')).data.user.id,eid=(await editor('me')).data.user.id;await superadmin('users/'+sid,'PATCH',{role:'SUB'});
const a=(await superadmin('categories','POST',{name:'A'})).data.id,b=(await sub('categories','POST',{name:'B'})).data.id;
const make=async(kind,categories,extra={})=>(await author('entries','POST',{kind,title:'test '+kind,content:'body stays unchanged',categories,...extra})).data.id;
const only=await make('thread',[a]),both=await make('thread',[a,b]),wiki=await make('wiki',[a]),pending=await make('thread',[a],{scheduledAt:new Date(Date.now()+86400000).toISOString(),scheduleListed:false}),secret=await make('thread',[a],{isSecret:true,secretPw:'test-secret'}),deleted=await make('thread',[a]);await superadmin('entries/'+deleted,'DELETE',{});
check((await sub('categories/'+a,'DELETE',{})).status===403,'subadmin cannot delete category');check((await author('categories/'+a,'DELETE',{})).status===403,'author cannot delete global category');check((await guest('categories/'+a,'DELETE',{})).status===401,'guest cannot delete category');
check((await superadmin('categories/'+a,'DELETE',{})).status===200,'superadmin can delete category');
check((await guest('categories')).data.every(c=>c.id!==a),'deleted category removed from catalog');
check((await author('entries/'+only)).data.categories==='[]','last category removal yields uncategorized thread');check((await author('entries/'+both)).data.categories===JSON.stringify([b]),'remaining category preserved');check((await author('entries/'+wiki)).data.categories==='[]','wiki reference removed too');
for(const call of [sub,author,editor])check((await call('uncategorized')).status===403,'uncategorized list denied to non-superadmin');check((await guest('uncategorized')).status===401,'uncategorized list denied to guest');
let list=(await superadmin('uncategorized')).data;check(list.total===3,'list includes ordinary, private and scheduled uncategorized threads only');check(list.entries.some(e=>e.id===secret)&&list.entries.some(e=>e.id===pending),'private and unlisted scheduled threads recoverable');check(list.entries.every(e=>!('content' in e)&&!('secret' in e)),'recovery list contains no body or password hash');
check((await superadmin('entries/'+secret+'/categories','PATCH',{categories:[b]})).status===200,'superadmin recategorizes private thread without exposing body');check((await superadmin('entries/'+secret)).status===403,'private body still requires password');
check((await author('entries/'+only+'/categories','PATCH',{categories:[b]})).status===200,'author assigns category');check((await author('entries/'+only)).data.content==='body stays unchanged','assignment leaves body intact');check((await superadmin('uncategorized')).data.total===1,'assigned threads disappear from recovery list');
check((await sub('entries/'+pending+'/categories','PATCH',{categories:[b]})).status===200,'subadmin assigns category to scheduled thread');
check((await author('entries/'+both+'/categories','PATCH',{categories:[]})).status===200,'author removes category');check((await editor('entries/'+both+'/categories','PATCH',{categories:[b]})).status===403,'unrelated user denied');
await author('entries/'+both+'/editors','POST',{userId:eid});check((await editor('entries/'+both+'/categories','PATCH',{categories:[b]})).status===403,'shared editor cannot change categories');check((await editor('entries/'+both,'PATCH',{title:'edited',content:'edited',categories:[b]})).status===403,'full edit cannot bypass category permission');check((await editor('entries/'+both,'PATCH',{title:'edited',content:'edited',categories:[]})).status===200,'shared editor can still edit body');
for(const categories of [[a],['missing'],{},[1],[b,b,b,b,'missing']])check((await author('entries/'+only+'/categories','PATCH',{categories})).status===400,'invalid/deleted category selection rejected');
check((await superadmin('categories/'+a,'DELETE',{})).status===404,'repeated deletion reports missing category');check((await author('entries/'+deleted+'/categories','PATCH',{categories:[b]})).status===404,'deleted thread cannot be recategorized');
console.log(`RESULT ${checks}/${checks}`);
