import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync,mkdirSync} from 'node:fs';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {build}=require(require.resolve('esbuild',{paths:[require.resolve('wrangler')]}));
const sql=new DatabaseSync(':memory:');
for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+f,'utf8'));
const DB={prepare(query){let args=[];const stmt={bind(...values){args=values;return stmt},async first(){return sql.prepare(query).get(...args)||null},async all(){return {results:sql.prepare(query).all(...args)}},async run(){const r=sql.prepare(query).run(...args);return {meta:{changes:Number(r.changes)}}}};return stmt},async batch(items){sql.exec('BEGIN');try{const r=[];for(const item of items)r.push(await item.run());sql.exec('COMMIT');return r}catch(e){sql.exec('ROLLBACK');throw e}}};
globalThis.testEnv={DB};
mkdirSync('.sites-runtime',{recursive:true});
await build({entryPoints:['app/api/[...path]/route.ts'],outfile:'.sites-runtime/limits-api.mjs',bundle:true,platform:'node',format:'esm',alias:{'@':process.cwd()},plugins:[{name:'isolated-db',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'env',namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},()=>({contents:'export const env=globalThis.testEnv;',loader:'js'}))}}]});
const api=await import('../.sites-runtime/limits-api.mjs');
async function call(path,body,ip='192.0.2.1',extra={}){const response=await api.POST(new Request('https://rp-land.rpland.workers.dev/api/'+path,{method:'POST',headers:{'Content-Type':'application/json',...(ip?{'CF-Connecting-IP':ip}:{}),...extra},body:JSON.stringify(body)}));return {status:response.status,data:await response.json(),cookie:response.headers.get('set-cookie')?.split(';')[0]}}
sql.exec("INSERT INTO sessions VALUES('expired','gone',0); INSERT INTO grants VALUES('expired','gone',0); INSERT INTO attempts VALUES('expired',1,0)");
assert.equal((await call('register',{username:'tester',password:'test-password'})).status,200);
for(const table of ['sessions','grants','attempts'])assert.equal(sql.prepare(`SELECT COUNT(*) n FROM ${table} WHERE expires=0`).get().n,0);
for(let i=0;i<20;i++)assert.equal((await call('login',{username:'tester',password:'wrong'})).status,401);
assert.equal((await call('login',{username:'tester',password:'test-password'})).status,429);
const other=await call('login',{username:'tester',password:'test-password'},'192.0.2.2');assert.equal(other.status,200);
assert.equal((await call('login',{username:'tester',password:'test-password'},'192.0.2.1',{'oai-authenticated-user-id':'forged'})).status,429);
assert.equal((await call('login',{username:'tester',password:'test-password'},null,{'oai-authenticated-user-id':'forged','X-Forwarded-For':'192.0.2.2'})).status,503);
assert.equal((await call('setup',{token:'anything'},'192.0.2.2',{Cookie:other.cookie})).status,503);
globalThis.testEnv.ADMIN_SETUP_TOKEN='test-only';
assert.equal((await call('setup',{token:'test-only'},'192.0.2.2',{Cookie:other.cookie})).status,200);
const entry=await call('entries',{title:'private',content:'body',isSecret:true,secretPw:'secret'},'192.0.2.2',{Cookie:other.cookie});assert.equal(entry.status,200);
for(let i=0;i<20;i++)assert.equal((await call(`entries/${entry.data.id}/unlock`,{password:'wrong'})).status,401);
assert.equal((await call(`entries/${entry.data.id}/unlock`,{password:'secret'})).status,429);
assert.equal((await call(`entries/${entry.data.id}/unlock`,{password:'secret'},'192.0.2.3')).status,200);
for(let i=0;i<12;i++)assert.equal((await call('register',{username:'visitor'+i,password:'test-password'},'192.0.2.'+(i+20))).status,200);
for(let i=0;i<20;i++)assert.equal((await call('register',{username:'tester',password:'test-password'},'192.0.2.200',{'oai-authenticated-user-id':'spoof'+i})).status,409);
assert.equal((await call('register',{username:'blocked',password:'test-password'},'192.0.2.200',{'oai-authenticated-user-id':'new-identity'})).status,429);
assert.equal((await call('maintenance/reset',{confirm:'RESET_ALL_RP_LAND'})).status,404);
assert.equal(sql.prepare('SELECT COUNT(*) n FROM users').get().n,13);
console.log('PASS real API with isolated SQLite: address isolation, forged headers, signup independence, setup errors, cleanup, disabled reset');
for(let i=0;i<65;i++)sql.prepare('INSERT INTO audit VALUES(?,?,?,?,?)').run('paging-'+i,null,'hide','test','2099-01-01T00:00:00.000Z');
const getAudit=async(page,cookie)=>{const r=await api.GET(new Request('https://rp-land.rpland.workers.dev/api/audit?page='+page,{headers:cookie?{Cookie:cookie}:{}}));return {status:r.status,data:await r.json()}};
assert.equal((await getAudit(1)).status,401);
const first=await getAudit(1,other.cookie),second=await getAudit(2,other.cookie);
assert.equal(first.status,200);assert.equal(first.data.entries.length,30);assert.equal(second.data.entries.length,30);
assert.ok(!first.data.entries.some(a=>second.data.entries.some(b=>a.id===b.id)));
assert.ok(first.data.total>=65);
assert.equal((await getAudit(0,other.cookie)).status,400);
console.log('PASS audit pagination, deterministic page boundaries and anonymous access rejection');
const getEntry=async(path,cookie)=>{const r=await api.GET(new Request('https://rp-land.rpland.workers.dev/api/'+path,{headers:cookie?{Cookie:cookie}:{}}));return {status:r.status,data:await r.json()}};
assert.equal((await getEntry(`entries/${entry.data.id}?include=comments`,other.cookie)).status,403);
const publicEntry=await call('entries',{title:'combined detail',content:'body'},'192.0.2.2',{Cookie:other.cookie});
assert.equal(publicEntry.status,200);
const publicId=publicEntry.data.id;
for(const content of ['visible text','hidden text','deleted text'])assert.equal((await call(`entries/${publicId}/comments`,{content},'192.0.2.2',{Cookie:other.cookie})).status,200);
sql.prepare("UPDATE comments SET hidden=1 WHERE content='hidden text'").run();
sql.prepare("UPDATE comments SET deleted=1 WHERE content='deleted text'").run();
const bundled=await getEntry(`entries/${publicId}?include=comments`),separate=await getEntry(`entries/${publicId}/comments`);
assert.equal(bundled.status,200);
assert.deepEqual(bundled.data.comments,separate.data);
assert.equal(bundled.data.comments.length,3);
assert.equal(bundled.data.comments[0].content,'visible text');
assert.equal(bundled.data.comments[1].content,'');
assert.equal(bundled.data.comments[2].content,'');
assert.equal(bundled.data.secret,undefined);
assert.equal((await getEntry(`entries/${publicId}`)).data.comments,undefined);
const wiki=await call('entries',{kind:'wiki',title:'wiki',content:'wiki body'},'192.0.2.2',{Cookie:other.cookie});
assert.deepEqual((await getEntry(`entries/${wiki.data.id}?include=comments`)).data.comments,[]);
const practice=await getEntry('entries/practice?include=comments');
assert.equal(practice.status,200);
assert.deepEqual(practice.data.comments,(await getEntry('entries/practice/comments')).data);
console.log('PASS combined detail: same replies and numbering, hidden/deleted redaction, secret access, wiki and practice');
sql.close();
