import assert from 'node:assert/strict';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {Rich} from '../components/rich-text';
import {anchorHref} from '../lib/rich-markup';
const id='12345678-1234-1234-1234-123456789abc';
const html=renderToStaticMarkup(<Rich text={'첫 줄\n둘째 [ruby=은하]銀河[/ruby] 다음 **굵은 [color=#cc3344]색[/color] 글씨**\n셋째\n\n[fold=열기]내용[/fold]'} />);
assert.match(html,/첫 줄<br\/>\n둘째/);
assert.match(html,/<ruby class="rp-ruby"><span class="rp-ruby-base">/);
assert.match(html,/<rt>은하<\/rt>/);
assert.match(html,/<strong>굵은 <span style="color:#cc3344">/);
assert.ok(!html.includes('<p><div'));
assert.equal(anchorHref({kind:'practice',entryId:'practice'},undefined,1),null);
assert.equal(anchorHref({kind:'thread',entryId:id},'practice',1),null);
assert.equal(anchorHref({kind:'practice'},id,1500),'?view=thread&id='+id+'#res-1500');
const anchors=renderToStaticMarkup(<Rich context={{kind:'practice'}} text={'>>1 >>>practice/1 >>>'+id+'/3'} />);
assert.equal((anchors.match(/<a /g)||[]).length,1);
assert.match(anchors,/>↗3<\/a>/);
assert.ok(!anchors.includes('&gt;&gt;&gt;'+id));
const literal=renderToStaticMarkup(<Rich text={'`[ruby=읽기]본문[/ruby]`'}/>);
assert.ok(!literal.includes('<ruby'));
console.log('PASS rich text: line breaks, ruby, nested styles, fold structure, anchors, code literals');
const gaps=renderToStaticMarkup(<Rich text={'첫째\n둘째\n\n\n셋째\n'}/>);
assert.match(gaps, /첫째<br\/>\n둘째/);
assert.match(gaps,/height:3.8em/);
assert.match(gaps,/height:1.9em/);
const formatting=renderToStaticMarkup(<Rich text={'*기울임* ++밑줄++ [transparent]감춤[/transparent]\n\n- 목록 하나\n- 목록 둘\n\n> 인용\n\n```\n[dice:1d6]\n```\n\n[링크](https://example.com) ![그림](https://example.com/image.png)'}/>);
assert.match(formatting,/<em>기울임<\/em>/);
assert.match(formatting,/<u>/);
assert.match(formatting,/class="rp-transparent" tabindex="0"/);
assert.match(formatting,/<ul>/);
assert.match(formatting,/<blockquote>/);
assert.match(formatting,/<pre><code>/);
assert.match(formatting,/href="https:\/\/example.com"/);
assert.match(formatting,/<img/);
const unsafe=renderToStaticMarkup(<Rich text={'<script>alert(1)</script> [위험](javascript:alert) [color=red;position:fixed]공격[/color]'}/>);
assert.ok(!unsafe.includes('<script'));
assert.ok(!unsafe.includes('href="javascript:'));
assert.ok(!unsafe.includes('style='));
const practiceLink=renderToStaticMarkup(<Rich text={'[연습장](?view=practice#res-1)'}/>);
assert.ok(!practiceLink.includes('<a '));
const recorded=renderToStaticMarkup(<Rich text={'결과 [dice:1x0..0]'} rolls={[{start:3,notation:'[dice:1x0..0]',sides:1,min:0,max:0,values:[0],total:0}]}/>);
assert.match(recorded,/class="dice"/);
assert.ok(!recorded.includes('등록할 때 굴림'));
console.log('PASS formatting, literal code, links, image markup, unsafe markup rejection, recorded zero dice');

const explicitDice=renderToStaticMarkup(<Rich text={'[dice:3x1..6!]'} rolls={[{start:0,notation:'[dice:3x1..6!]',sides:6,min:1,max:6,unique:true,values:[5,6,2],total:13}]}/>);
assert.match(explicitDice,/\[dice:3x1\.\.6!= 5, 6, 2 · 합계 13\]/);
const singleDice=renderToStaticMarkup(<Rich text={'[dice:1x0..0-5]'} rolls={[{start:0,notation:'[dice:1x0..0-5]',sides:1,values:[-5],total:-5}]}/>);
assert.match(singleDice,/\[dice:1x0\.\.0-5= -5\]/);
console.log('PASS visible dice notation with unique rolls, totals and signed results');

const shortImages=renderToStaticMarkup(<Rich text={'!(https://example.com/a.png) !(/favicon.svg) `!(https://example.com/code.png)` !(javascript:alert)'} />);
assert.equal((shortImages.match(/<img /g)||[]).length,2);
assert.match(shortImages, /<code>!\(https:\/\/example.com\/code.png\)<\/code>/);
assert.ok(!shortImages.includes('src="javascript:'));
console.log('PASS short image syntax, code literal and unsafe URL rejection');

const mixedImages=renderToStaticMarkup(<Rich text={'![캐릭터의 모습](https://example.com/character.png)\n![](https://example.com/empty.png)\n!(https://example.com/short.png)\n![밤하늘](https://example.com/night.png "별이 빛나는 밤")'} />);
assert.equal((mixedImages.match(/<img /g)||[]).length,4);
const imageTags=mixedImages.match(/<img [^>]*>/g)||[];
for(const [file,alt] of [['character','캐릭터의 모습'],['empty',''],['short',''],['night','밤하늘']]){
  const tag=imageTags.find(tag=>tag.includes(`src="https://example.com/${file}.png"`));
  assert.ok(tag,`image URL preserved: ${file}`);
  assert.ok(tag.includes(`alt="${alt}"`),`image description preserved: ${file}`);
}
assert.ok(imageTags.some(tag=>tag.includes('title="별이 빛나는 밤"')));
console.log('PASS mixed image forms preserve URLs, Korean descriptions and titles');
