import assert from 'node:assert/strict';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {Rich} from '../components/rich-text';
import {anchorHref} from '../lib/rich-markup';
const id='12345678-1234-1234-1234-123456789abc';
const html=renderToStaticMarkup(<Rich text={'첫 줄\n둘째 [ruby=은하]銀河[/ruby] 다음 **굵은 [color=#cc3344]색[/color] 글씨**\n셋째\n\n[fold=열기]내용[/fold]'} />);
assert.match(html,/첫 줄<br\/>\n둘째/);
assert.match(html,/<ruby class="rp-ruby"><span class="rp-ruby-base">/);
assert.match(html,/<rt>은하<\/rt>/);
assert.match(html,/<strong>굵은 <span style="color:#cc3344">/);
assert.ok(!html.includes('<p><div'));
assert.equal(anchorHref({kind:'practice',entryId:'practice'},undefined,1),null);
assert.equal(anchorHref({kind:'thread',entryId:id},'practice',1),null);
assert.equal(anchorHref({kind:'practice'},id,1500),'?view=thread&id='+id+'#res-1500');
const anchors=renderToStaticMarkup(<Rich context={{kind:'practice'}} text={'>>1 >>>practice/1 >>>'+id+'/3'} />);
assert.equal((anchors.match(/<a /g)||[]).length,1);
const literal=renderToStaticMarkup(<Rich text={'`[ruby=읽기]본문[/ruby]`'}/>);
assert.ok(!literal.includes('<ruby'));
console.log('PASS rich text: line breaks, ruby, nested styles, fold structure, anchors, code literals');
const gaps=renderToStaticMarkup(<Rich text={'첫째\n둘째\n\n\n셋째\n'}/>);
assert.match(gaps, /첫째<br\/>\n둘째/);
assert.match(gaps,/height:3.8em/);
assert.match(gaps,/height:1.9em/);
