'use client';
import {useEffect,useState} from 'react';
type Activity={id:string;action:string;created:string;actor:string|null;target:string};
const labels:Record<string,string>={'setup':'총관리자 지정','update-account':'계정 정보 변경','withdraw':'회원 탈퇴','deactivate':'회원 탈퇴 처리','delete-category':'카테고리 삭제','set-entry-categories':'글 분류 변경','unlock':'비밀 스레드 열람','view-entry-password':'비밀글 비밀번호 확인','delete-practice-comment':'연습장 레스 삭제','delete-comment':'레스 삭제','hide':'레스 가리기','unhide':'레스 가림 해제','delete-entry':'문서 삭제','role:SUB':'부관리자 임명','role:USER':'일반회원으로 변경'};
export function ActivityPage(){
 const[page,setPage]=useState(1),[revision,setRevision]=useState(0),[rows,setRows]=useState<Activity[]>([]),[total,setTotal]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');fetch(`/api/audit?page=${page}`,{signal:controller.signal}).then(async r=>{const d=await r.json() as {entries:Activity[];total:number;error?:string};if(!r.ok)throw new Error(d.error||'관리활동을 불러오지 못했습니다.');return d}).then(d=>{setRows(d.entries);setTotal(d.total)}).catch(e=>{if(!controller.signal.aborted)setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[page,revision]);
 return <div className="panel article"><div className="heading"><p>최근 기록부터 30개씩 표시합니다.</p><button className="btn" disabled={loading} onClick={()=>setRevision(v=>v+1)}>새로고침</button></div>{error?<p className="error" role="alert">{error}</p>:loading?<p role="status">불러오는 중…</p>:rows.length?rows.map(row=><div className="activity-row" key={row.id}><div><strong>{labels[row.action]||row.action}</strong><small className="muted">{new Date(row.created).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</small></div><details><summary>상세 정보</summary><p>계정 ID: {row.actor||'비로그인'}<br/>대상 ID: {row.target}</p></details></div>):<p className="muted">관리 기록이 없습니다.</p>}<nav className="actions" aria-label="관리활동 페이지" style={{marginTop:16}}><button className="btn" disabled={loading||page===1} onClick={()=>setPage(v=>v-1)}>이전</button><span>{page} / {Math.max(1,Math.ceil(total/30))}</span><button className="btn" disabled={loading||!!error||page*30>=total} onClick={()=>setPage(v=>v+1)}>다음</button></nav></div>;
}
