'use client';
import {useState} from 'react';
import {X} from 'lucide-react';
import {Sheet,SheetContent,SheetTitle,SheetDescription,SheetClose} from '@/components/ui/sheet';
import {calculate} from '@/lib/calculator';
export function CalculatorSidebar({open,onOpenChange}:{open:boolean;onOpenChange:(open:boolean)=>void}){
 const[expression,setExpression]=useState(''),[history,setHistory]=useState<{expression:string;result:number}[]>([]),[error,setError]=useState('');
 function run(){try{const result=calculate(expression);setHistory(h=>[{expression,result},...h].slice(0,50));setExpression(String(result));setError('')}catch(e){setError((e as Error).message)}}
 return <Sheet modal={false} open={open} onOpenChange={onOpenChange}><SheetContent className="calculator-sidebar" showCloseButton={false} onInteractOutside={e=>e.preventDefault()} onOpenAutoFocus={e=>e.preventDefault()} onCloseAutoFocus={e=>e.preventDefault()}><div className="calculator-heading"><SheetTitle>계산기</SheetTitle><SheetClose className="btn" aria-label="계산기 닫기"><X size={18}/></SheetClose></div><SheetDescription>스레드를 나가면 기록이 지워집니다.</SheetDescription><form onSubmit={e=>{e.preventDefault();run()}}><input aria-label="계산 수식" value={expression} maxLength={300} placeholder="(10 + 5) × 2" onChange={e=>setExpression(e.target.value)}/><div className="calculator-keys">{['7','8','9','÷','4','5','6','×','1','2','3','-','0','.','(',')','%','+'].map(key=><button className="btn" type="button" key={key} onClick={()=>setExpression(x=>(x+key).slice(0,300))}>{key}</button>)}<button type="button" className="btn" onClick={()=>setExpression(x=>x.slice(0,-1))} aria-label="한 글자 지우기">⌫</button><button type="button" className="btn" onClick={()=>{setExpression('');setError('')}}>C</button></div><button className="btn primary" type="submit">계산 =</button></form>{error&&<p className="error" role="alert">{error}</p>}<div className="calculator-heading"><h3>계산 기록</h3><button className="btn" onClick={()=>setHistory([])}>기록 지우기</button></div><ol className="calculator-history">{history.map((item,i)=><li key={i}><span>{item.expression}</span><button className="btn" title="결과를 수식으로 사용" onClick={()=>setExpression(String(item.result))}>= {item.result}</button></li>)}</ol></SheetContent></Sheet>
}
