'use client';
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {toast} from 'sonner';
async function call(path:string,body?:unknown){const response=await fetch('/api/'+path,body?{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined);const data=await response.json() as any;if(!response.ok)throw new Error(data.error);return data}
export function CategoryAssignment({id,current=[],onSaved}:{id:string;current?:string[];onSaved:()=>void}){
 const[open,setOpen]=useState(false),[options,setOptions]=useState<{id:string;name:string}[]>([]),[selected,setSelected]=useState<string[]>([]),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState('');
 async function start(){setOpen(true);setLoading(true);setError('');try{const cats=await call('categories');setOptions(cats);setSelected(current.filter(id=>cats.some((c:{id:string})=>c.id===id)))}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 return <><button className="btn" onClick={()=>void start()}>카테고리 변경</button><Dialog open={open} onOpenChange={value=>{if(!busy)setOpen(value)}}><DialogContent><DialogTitle>카테고리 변경</DialogTitle><DialogDescription>최대 3개를 선택하세요. 모두 해제하면 미분류로 남습니다.</DialogDescription>{error&&<p className="error" role="alert">{error}</p>}{loading?<p>불러오는 중…</p>:<div className="filters">{options.map(c=><label className="check-label" key={c.id}><Checkbox checked={selected.includes(c.id)} disabled={busy||(!selected.includes(c.id)&&selected.length>=3)} onCheckedChange={checked=>setSelected(ids=>checked?[...ids,c.id]:ids.filter(id=>id!==c.id))}/>{c.name}</label>)}{!options.length&&<p>등록된 카테고리가 없습니다. 관리자가 먼저 카테고리를 만들어 주세요.</p>}</div>}<button className="btn primary" disabled={busy||loading||!!error} onClick={async()=>{setBusy(true);try{await call('entries/'+id+'/categories',{categories:selected});setOpen(false);toast.success('카테고리를 변경했습니다.');onSaved()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>저장</button></DialogContent></Dialog></>
}
export function UncategorizedThreads({revision}:{revision:number}){
 const[rows,setRows]=useState<any[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[refresh,setRefresh]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{let active=true;setLoading(true);setError('');call('uncategorized?page='+page).then(d=>{if(!active)return;if(!d.entries.length&&page>1){setPage(p=>p-1);return}setRows(d.entries);setTotal(d.total)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[revision,page,refresh]);
 return <section className="uncategorized-threads"><h2>미분류 스레드 <span className="tag">{total}</span></h2><p className="muted">카테고리가 없는 스레드입니다. 비밀·예약 스레드도 포함됩니다.</p>{error&&<p className="error" role="alert">{error}</p>}<button className="btn" disabled={loading} onClick={()=>setRefresh(v=>v+1)}>목록 새로고침</button>{loading?<p>불러오는 중…</p>:rows.length?rows.map(r=><div className="uncategorized-row" key={r.id}><div><strong>{r.title}</strong><div className="meta">{r.is_secret===1&&<span>비밀</span>}{r.scheduled_at&&new Date(r.scheduled_at).getTime()>Date.now()&&<span>예약</span>}</div></div><CategoryAssignment id={r.id} onSaved={()=>setRefresh(v=>v+1)}/></div>):!error&&<p className="muted">미분류 스레드가 없습니다.</p>}{total>20&&<div className="actions"><button className="btn" disabled={loading||page<=1} onClick={()=>setPage(p=>p-1)}>이전</button><span>{page} / {Math.ceil(total/20)}</span><button className="btn" disabled={loading||page*20>=total} onClick={()=>setPage(p=>p+1)}>다음</button></div>}</section>
}
